INSERT INTO users (id, username, email, phone, password) VALUES (1, 'user1', 'user1@example.com', '1234567890', '1234');
INSERT INTO users (id, username, email, phone, password) VALUES (2, 'user2', 'user2@example.com', '1234567890', '1234');
INSERT INTO users (id, username, email, phone, password) VALUES (3, 'user3', 'user3@example.com', '1234567890', '1234');
INSERT INTO users (id, username, email, phone, password) VALUES (4, 'user4', 'user4@example.com', '1234567890', '1234');
INSERT INTO users (id, username, email, phone, password) VALUES (5, 'user5', 'user5@example.com', '1234567890', '1234');
INSERT INTO users (id, username, email, phone, password) VALUES (6, 'user6', 'user6@example.com', '1234567890', '1234');
INSERT INTO users (id, username, email, phone, password) VALUES (7, 'user7', 'user7@example.com', '1234567890', '1234');
INSERT INTO users (id, username, email, phone, password) VALUES (8, 'user8', 'user8@example.com', '1234567890', '1234');
INSERT INTO users (id, username, email, phone, password) VALUES (9, 'user9', 'user9@example.com', '1234567890', '1234');
INSERT INTO users (id, username, email, phone, password) VALUES (10, 'user10', 'user10@example.com', '1234567890', '1234');
INSERT INTO users (id, username, email, phone, password) VALUES (11, 'user11', 'user11@example.com', '1234567890', '1234');
INSERT INTO users (id, username, email, phone, password) VALUES (12, 'user12', 'user12@example.com', '1234567890', '1234');
INSERT INTO users (id, username, email, phone, password) VALUES (13, 'user13', 'user13@example.com', '1234567890', '1234');
INSERT INTO users (id, username, email, phone, password) VALUES (14, 'user14', 'user14@example.com', '1234567890', '1234');
INSERT INTO users (id, username, email, phone, password) VALUES (15, 'user15', 'user15@example.com', '1234567890', '1234');
INSERT INTO users (id, username, email, phone, password) VALUES (16, 'user16', 'user16@example.com', '1234567890', '1234');
INSERT INTO users (id, username, email, phone, password) VALUES (17, 'user17', 'user17@example.com', '1234567890', '1234');
INSERT INTO users (id, username, email, phone, password) VALUES (18, 'user18', 'user18@example.com', '1234567890', '1234');
INSERT INTO users (id, username, email, phone, password) VALUES (19, 'user19', 'user19@example.com', '1234567890', '1234');
INSERT INTO users (id, username, email, phone, password) VALUES (20, 'user20', 'user20@example.com', '1234567890', '1234');
INSERT INTO users (id, username, email, phone, password) VALUES (21, 'user21', 'user21@example.com', '1234567890', '1234');
INSERT INTO users (id, username, email, phone, password) VALUES (22, 'user22', 'user22@example.com', '1234567890', '1234');
INSERT INTO users (id, username, email, phone, password) VALUES (23, 'user23', 'user23@example.com', '1234567890', '1234');
INSERT INTO users (id, username, email, phone, password) VALUES (24, 'user24', 'user24@example.com', '1234567890', '1234');
INSERT INTO users (id, username, email, phone, password) VALUES (25, 'user25', 'user25@example.com', '1234567890', '1234');
INSERT INTO users (id, username, email, phone, password) VALUES (26, 'user26', 'user26@example.com', '1234567890', '1234');
INSERT INTO users (id, username, email, phone, password) VALUES (27, 'user27', 'user27@example.com', '1234567890', '1234');
INSERT INTO users (id, username, email, phone, password) VALUES (28, 'user28', 'user28@example.com', '1234567890', '1234');
INSERT INTO users (id, username, email, phone, password) VALUES (29, 'user29', 'user29@example.com', '1234567890', '1234');
INSERT INTO users (id, username, email, phone, password) VALUES (30, 'user30', 'user30@example.com', '1234567890', '1234');
INSERT INTO users (id, username, email, phone, password) VALUES (31, 'user31', 'user31@example.com', '1234567890', '1234');
INSERT INTO users (id, username, email, phone, password) VALUES (32, 'user32', 'user32@example.com', '1234567890', '1234');
INSERT INTO users (id, username, email, phone, password) VALUES (33, 'user33', 'user33@example.com', '1234567890', '1234');
INSERT INTO users (id, username, email, phone, password) VALUES (34, 'user34', 'user34@example.com', '1234567890', '1234');
INSERT INTO users (id, username, email, phone, password) VALUES (35, 'user35', 'user35@example.com', '1234567890', '1234');
INSERT INTO users (id, username, email, phone, password) VALUES (36, 'user36', 'user36@example.com', '1234567890', '1234');
INSERT INTO users (id, username, email, phone, password) VALUES (37, 'user37', 'user37@example.com', '1234567890', '1234');
INSERT INTO users (id, username, email, phone, password) VALUES (38, 'user38', 'user38@example.com', '1234567890', '1234');
INSERT INTO users (id, username, email, phone, password) VALUES (39, 'user39', 'user39@example.com', '1234567890', '1234');
INSERT INTO users (id, username, email, phone, password) VALUES (40, 'user40', 'user40@example.com', '1234567890', '1234');
INSERT INTO users (id, username, email, phone, password) VALUES (41, 'user41', 'user41@example.com', '1234567890', '1234');
INSERT INTO users (id, username, email, phone, password) VALUES (42, 'user42', 'user42@example.com', '1234567890', '1234');
INSERT INTO users (id, username, email, phone, password) VALUES (43, 'user43', 'user43@example.com', '1234567890', '1234');
INSERT INTO users (id, username, email, phone, password) VALUES (44, 'user44', 'user44@example.com', '1234567890', '1234');
INSERT INTO users (id, username, email, phone, password) VALUES (45, 'user45', 'user45@example.com', '1234567890', '1234');
INSERT INTO users (id, username, email, phone, password) VALUES (46, 'user46', 'user46@example.com', '1234567890', '1234');
INSERT INTO users (id, username, email, phone, password) VALUES (47, 'user47', 'user47@example.com', '1234567890', '1234');
INSERT INTO users (id, username, email, phone, password) VALUES (48, 'user48', 'user48@example.com', '1234567890', '1234');
INSERT INTO users (id, username, email, phone, password) VALUES (49, 'user49', 'user49@example.com', '1234567890', '1234');
INSERT INTO users (id, username, email, phone, password) VALUES (50, 'user50', 'user50@example.com', '1234567890', '1234');
INSERT INTO reviews (id, product_id, reviewer_id, rating, text_review) VALUES (REVIEW_SEQ.NEXTVAL, 50, 1, 1, ': The quiet functionality is a standout feature, ideal for a peaceful environment.');
INSERT INTO reviews (id, product_id, reviewer_id, rating, text_review) VALUES (REVIEW_SEQ.NEXTVAL, 64, 2, 3, ': The versatility of this device is impressive, adapting well to various needs.');
INSERT INTO reviews (id, product_id, reviewer_id, rating, text_review) VALUES (REVIEW_SEQ.NEXTVAL, 100, 3, 1, ': A very affordable product, providing excellent features at a reasonable price.');
INSERT INTO reviews (id, product_id, reviewer_id, rating, text_review) VALUES (REVIEW_SEQ.NEXTVAL, 41, 4, 3, ': The fast performance of this product is a major plus for me.');
INSERT INTO reviews (id, product_id, reviewer_id, rating, text_review) VALUES (REVIEW_SEQ.NEXTVAL, 92, 5, 1, ': An excellent high-capacity product that meets my demanding requirements.');
INSERT INTO reviews (id, product_id, reviewer_id, rating, text_review) VALUES (REVIEW_SEQ.NEXTVAL, 102, 6, 1, ': I am impressed by the smart technology integrated into this device.');
INSERT INTO reviews (id, product_id, reviewer_id, rating, text_review) VALUES (REVIEW_SEQ.NEXTVAL, 90, 7, 1, ': I love its high-capacity feature, which allows for extended use without frequent refills or changes.');
INSERT INTO reviews (id, product_id, reviewer_id, rating, text_review) VALUES (REVIEW_SEQ.NEXTVAL, 10, 8, 1, ': The innovative features of this product set it apart from the competition.');
INSERT INTO reviews (id, product_id, reviewer_id, rating, text_review) VALUES (REVIEW_SEQ.NEXTVAL, 63, 9, 4, ': It’s an affordable option that delivers excellent performance.');
INSERT INTO reviews (id, product_id, reviewer_id, rating, text_review) VALUES (REVIEW_SEQ.NEXTVAL, 51, 10, 5, ': This product is not only functional but also very stylish.');
INSERT INTO reviews (id, product_id, reviewer_id, rating, text_review) VALUES (REVIEW_SEQ.NEXTVAL, 82, 11, 5, ': I appreciate how user-friendly this device is, with intuitive controls.');
INSERT INTO reviews (id, product_id, reviewer_id, rating, text_review) VALUES (REVIEW_SEQ.NEXTVAL, 92, 12, 2, ': The high capacity of this product is perfect for my needs.');
INSERT INTO reviews (id, product_id, reviewer_id, rating, text_review) VALUES (REVIEW_SEQ.NEXTVAL, 101, 13, 1, ': Safety is clearly a priority with this product, and it shows.');
INSERT INTO reviews (id, product_id, reviewer_id, rating, text_review) VALUES (REVIEW_SEQ.NEXTVAL, 102, 14, 2, ': The smart capabilities of this device are a game-changer, offering great convenience.');
INSERT INTO reviews (id, product_id, reviewer_id, rating, text_review) VALUES (REVIEW_SEQ.NEXTVAL, 32, 15, 5, ': Its a very reliable product, never failing to meet my expectations.');
INSERT INTO reviews (id, product_id, reviewer_id, rating, text_review) VALUES (REVIEW_SEQ.NEXTVAL, 53, 16, 4, ': This product operates so quietly, its barely noticeable.');
INSERT INTO reviews (id, product_id, reviewer_id, rating, text_review) VALUES (REVIEW_SEQ.NEXTVAL, 54, 17, 5, ': Its ergonomic features ensure that using it is a pleasant experience.');
INSERT INTO reviews (id, product_id, reviewer_id, rating, text_review) VALUES (REVIEW_SEQ.NEXTVAL, 73, 18, 2, ': I feel confident using this device because of its excellent safety features.');
INSERT INTO reviews (id, product_id, reviewer_id, rating, text_review) VALUES (REVIEW_SEQ.NEXTVAL, 94, 19, 2, ': I feel confident using this device because of its excellent safety features.');
INSERT INTO reviews (id, product_id, reviewer_id, rating, text_review) VALUES (REVIEW_SEQ.NEXTVAL, 113, 20, 2, ': The high capacity of this product is perfect for my needs.');
INSERT INTO reviews (id, product_id, reviewer_id, rating, text_review) VALUES (REVIEW_SEQ.NEXTVAL, 81, 21, 1, ': An exceptionally ergonomic product that reduces strain during use.');
INSERT INTO reviews (id, product_id, reviewer_id, rating, text_review) VALUES (REVIEW_SEQ.NEXTVAL, 92, 22, 3, ': This device offers high capacity, making it very convenient for heavy-duty tasks.');
INSERT INTO reviews (id, product_id, reviewer_id, rating, text_review) VALUES (REVIEW_SEQ.NEXTVAL, 41, 23, 4, ': This product is very fast, significantly reducing wait times.');
INSERT INTO reviews (id, product_id, reviewer_id, rating, text_review) VALUES (REVIEW_SEQ.NEXTVAL, 32, 24, 5, ': The reliability of this device is outstanding, ensuring continuous performance.');
INSERT INTO reviews (id, product_id, reviewer_id, rating, text_review) VALUES (REVIEW_SEQ.NEXTVAL, 82, 25, 3, ': This product is very user-friendly, making it easy to operate.');
INSERT INTO reviews (id, product_id, reviewer_id, rating, text_review) VALUES (REVIEW_SEQ.NEXTVAL, 10, 26, 1, ': The innovative features of this product set it apart from the competition.');
INSERT INTO reviews (id, product_id, reviewer_id, rating, text_review) VALUES (REVIEW_SEQ.NEXTVAL, 34, 27, 5, ': I love how this device consumes minimal power without compromising performance.');
INSERT INTO reviews (id, product_id, reviewer_id, rating, text_review) VALUES (REVIEW_SEQ.NEXTVAL, 101, 28, 3, ': A very safe product, well-designed to prevent accidents.');
INSERT INTO reviews (id, product_id, reviewer_id, rating, text_review) VALUES (REVIEW_SEQ.NEXTVAL, 90, 29, 5, ': The high capacity of this product is perfect for my needs.');
INSERT INTO reviews (id, product_id, reviewer_id, rating, text_review) VALUES (REVIEW_SEQ.NEXTVAL, 53, 30, 2, ': Its amazing how this device performs so well while being so quiet.');
INSERT INTO reviews (id, product_id, reviewer_id, rating, text_review) VALUES (REVIEW_SEQ.NEXTVAL, 50, 31, 1, ': This product operates so quietly, its barely noticeable.');
INSERT INTO reviews (id, product_id, reviewer_id, rating, text_review) VALUES (REVIEW_SEQ.NEXTVAL, 11, 32, 1, ': This product operates so quietly, its barely noticeable.');
INSERT INTO reviews (id, product_id, reviewer_id, rating, text_review) VALUES (REVIEW_SEQ.NEXTVAL, 32, 33, 4, ': I trust this device because of its proven reliability.');
INSERT INTO reviews (id, product_id, reviewer_id, rating, text_review) VALUES (REVIEW_SEQ.NEXTVAL, 102, 34, 4, ': Truly a smart product, with intelligent features that enhance usability.');
INSERT INTO reviews (id, product_id, reviewer_id, rating, text_review) VALUES (REVIEW_SEQ.NEXTVAL, 30, 35, 3, ': A very stylish product that combines aesthetics with functionality.');
INSERT INTO reviews (id, product_id, reviewer_id, rating, text_review) VALUES (REVIEW_SEQ.NEXTVAL, 32, 36, 4, ': Its a very reliable product, never failing to meet my expectations.');
INSERT INTO reviews (id, product_id, reviewer_id, rating, text_review) VALUES (REVIEW_SEQ.NEXTVAL, 113, 37, 4, ': This device offers high capacity, making it very convenient for heavy-duty tasks.');
INSERT INTO reviews (id, product_id, reviewer_id, rating, text_review) VALUES (REVIEW_SEQ.NEXTVAL, 91, 38, 5, ': An excellent energy-saving option, perfect for those looking to reduce their carbon footprint.');
INSERT INTO reviews (id, product_id, reviewer_id, rating, text_review) VALUES (REVIEW_SEQ.NEXTVAL, 114, 39, 5, ': A highly user-friendly product, perfect for people of all skill levels.');
INSERT INTO reviews (id, product_id, reviewer_id, rating, text_review) VALUES (REVIEW_SEQ.NEXTVAL, 62, 40, 5, ': I appreciate its versatility, making it a handy tool for different tasks.');
INSERT INTO reviews (id, product_id, reviewer_id, rating, text_review) VALUES (REVIEW_SEQ.NEXTVAL, 41, 41, 2, ': The fast performance of this product is a major plus for me.');
INSERT INTO reviews (id, product_id, reviewer_id, rating, text_review) VALUES (REVIEW_SEQ.NEXTVAL, 112, 42, 3, ': The versatility of this device is impressive, adapting well to various needs.');
INSERT INTO reviews (id, product_id, reviewer_id, rating, text_review) VALUES (REVIEW_SEQ.NEXTVAL, 21, 43, 4, ': The quiet functionality is a standout feature, ideal for a peaceful environment.');
INSERT INTO reviews (id, product_id, reviewer_id, rating, text_review) VALUES (REVIEW_SEQ.NEXTVAL, 72, 44, 5, ': I am impressed with its robust construction and long-lasting performance.');
INSERT INTO reviews (id, product_id, reviewer_id, rating, text_review) VALUES (REVIEW_SEQ.NEXTVAL, 114, 45, 4, ': Its user-friendly design ensures a hassle-free experience.');
INSERT INTO reviews (id, product_id, reviewer_id, rating, text_review) VALUES (REVIEW_SEQ.NEXTVAL, 54, 46, 3, ': I love how ergonomic this device is, making it easy to handle for long periods.');
INSERT INTO reviews (id, product_id, reviewer_id, rating, text_review) VALUES (REVIEW_SEQ.NEXTVAL, 41, 47, 1, ': It operates at a great speed, making tasks quicker and easier.');
INSERT INTO reviews (id, product_id, reviewer_id, rating, text_review) VALUES (REVIEW_SEQ.NEXTVAL, 82, 48, 2, ': A highly user-friendly product, perfect for people of all skill levels.');
INSERT INTO reviews (id, product_id, reviewer_id, rating, text_review) VALUES (REVIEW_SEQ.NEXTVAL, 91, 49, 1, ': Remarkably efficient in energy usage, making it an eco-friendly choice.');
INSERT INTO reviews (id, product_id, reviewer_id, rating, text_review) VALUES (REVIEW_SEQ.NEXTVAL, 73, 50, 3, ': The safety features are top-notch, providing peace of mind during use.');
